In [1]:
!pip install numpy matplotlib scikit-learn torchvision pillow opencv-python

In [2]:
!pip install scikit-learn opencv-python matplotlib


In [3]:
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Function to extract features from an image
def extract_features(image_path):
    # Load image
    img = cv2.imread(image_path)
    
    # Resize to standard dimensions
    img = cv2.resize(img, (128, 128))

    # Convert image to RGB
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Calculate color histogram (using 3 channels: red, green, blue)
    hist = cv2.calcHist([img_rgb], [0, 1, 2], None, [8, 8, 8], [0, 256, 0, 256, 0, 256])

    # Normalize the histogram
    hist = cv2.normalize(hist, hist).flatten()
    
    return hist

# Function to load images and prepare dataset
def prepare_dataset(image_folder):
    features = []
    labels = []
    flower_classes = os.listdir(image_folder)

    # Iterate over each class of flowers
    for flower_class in flower_classes:
        flower_class_folder = os.path.join(image_folder, flower_class)
        if os.path.isdir(flower_class_folder):
            for image_file in os.listdir(flower_class_folder):
                image_path = os.path.join(flower_class_folder, image_file)

                # Extract features from the image
                feature = extract_features(image_path)

                # Append feature and label to the dataset
                features.append(feature)
                labels.append(flower_class)
    
    return np.array(features), np.array(labels)

# Prepare dataset
image_folder = r"C:/Users/Formi/Arya/Sem6/CVI/Assignmetn3/train"
if os.path.exists(image_folder):
    print(f"Folder found: {image_folder}")
else:
    print(f"Folder not found: {image_folder}")
          
# Prepare data and labels
X, y = prepare_dataset(image_folder)

# Split dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train KNN model
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# Predict on the test set
y_pred = knn.predict(X_test)

# Evaluate the model
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Function to classify a single image
def classify_flower(image_path):
    # Extract features from the input image
    feature = extract_features(image_path)

    # Predict the flower class
    flower_class = knn.predict([feature])[0]
    
    # Display the result
    print(f"The flower in the image is classified as: {flower_class}")

    # Show the input image
    img = cv2.imread(image_path)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.imshow(img_rgb)
    plt.title(f"Predicted: {flower_class}")
    plt.show()

# Example usage: choosing an image path
image_path = 'C:\\Users\\Formi\\Arya\\Sem6\\CVI\\3179751458_9646d839f6_n.jpg'  # Specify the path to your image here
classify_flower(image_path)


Folder found: C:/Users/Formi/Arya/Sem6/CVI/Assignmetn3/train
Accuracy: 0.4393203883495146
Confusion Matrix:
[[89 39  6  8 14]
 [64 86  6 12 15]
 [30 42 47  8 27]
 [28 38  6 70 11]
 [47 34 18  9 70]]
Classification Report:
              precision    recall  f1-score   support

       daisy       0.34      0.57      0.43       156
   dandelion       0.36      0.47      0.41       183
        rose       0.57      0.31      0.40       154
   sunflower       0.65      0.46      0.54       153
       tulip       0.51      0.39      0.44       178

    accuracy                           0.44       824
   macro avg       0.49      0.44      0.44       824
weighted avg       0.48      0.44      0.44       824



error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
